---
- name: Create xibo user
  user:
    name: "{{ xibo_user }}"

- name: Configure autologin
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: 0644

- name: Disable human interface driver module
  template:
    src: usbhid.conf.j2
    dest: /etc/modprobe.d/usbhid.conf
    owner: root
    group: root
    mode: 0755
  when: xibo_hid_module == "disabled"
  notify: Configure initramfs

- name: Enable human interface driver module
  file:
    path: /etc/modprobe.d/usbhid.conf
    state: absent
  when: xibo_hid_module == "enabled"
  notify: Configure initramfs

- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: true
  register: snapd

- name: Ensure snap is started and enabled on boot
  ansible.builtin.systemd:
    enabled: true
    name: snapd
    state: started
  notify: Restart udev

- name: Ensure snap core is installed
  community.general.snap:
    name: core
    state: present

- name: Ensure snap xibo-player is installed
  community.general.snap:
    name: xibo-player
    state: present

- name: Create autostart folder
  file:
    path: /home/{{ xibo_user }}/.config/autostart/
    state: directory
    owner: "{{ xibo_user }}"
    group: "{{ xibo_user }}"
    mode: 0755

- name: Configure Xibo autostart
  template:
    src: xibo.desktop.j2
    dest: /home/{{ xibo_user }}/.config/autostart/xibo.desktop
    owner: "{{ xibo_user }}"
    group: "{{ xibo_user }}"
    mode: 0777

- name: Create Xibo resources directory
  file:
    path: /home/{{ xibo_user }}/snap/xibo-player/common/resources
    state: directory
    owner: "{{ xibo_user }}"
    group: "{{ xibo_user }}"
    mode: 0755

- name: Configure xibo player
  template:
    src: cmsSettings.xml.j2
    dest: /home/{{ xibo_user }}/snap/xibo-player/common/cmsSettings.xml
    owner: "{{ xibo_user }}"
    group: "{{ xibo_user }}"
    mode: 0755

