---
- name: Create xibo user
  user:
    name: "{{ xibo_linux_user }}"

- name: Get UIDs
  getent:
    database: passwd # This registers the variable getent_passwd used in our template

- name: Install required apt packages
  apt:
    name:
      - dbus-user-session
      - snapd
      - xorg

- name: Install required snap packages
  community.general.snap:
    name:
      - core
      - xibo-player

- name: Create xorg socket
  template:
    src: xorg.socket.j2
    dest: /etc/systemd/system/xorg.socket
  notify:
    - Reload systemd configuration
    - Restart xibo-linux service

- name: Create xorg service
  template:
    src: xorg.service.j2
    dest: /etc/systemd/system/xorg.service
  notify:
    - Reload systemd configuration

- name: Create xibo-linux service
  template:
    src: xibo-linux.service.j2
    dest: /etc/systemd/system/xibo-linux.service
  notify:
    - Reload systemd configuration
    - Restart xibo-linux service

- name: Create udev rule for monitor hotplug
  template:
    src: monitor-hotplug.rules.j2
    dest: /etc/udev/rules.d/95-xibo-linux-monitor-hotplug.rules
  notify:
    - Reload udev rules

- name: Create Xibo resources directory
  file:
    path: /home/{{ xibo_linux_user }}/snap/xibo-player/common/resources
    state: directory
    owner: "{{ xibo_linux_user }}"
    group: "{{ xibo_linux_user }}"
    mode: 0755
  notify:
    - Restart xibo-linux service

- name: Configure Xibo Linux player
  template:
    src: cmsSettings.xml.j2
    dest: /home/{{ xibo_linux_user }}/snap/xibo-player/common/cmsSettings.xml
    owner: "{{ xibo_linux_user }}"
    group: "{{ xibo_linux_user }}"
    mode: 0644
  notify:
    - Restart xibo-linux service

- name: Enable xorg socket
  systemd:
    name: xorg.socket
    enabled: True
    state: started

- meta: flush_handlers

- name: Enable xibo-linux service
  systemd:
    name: xibo-linux.service
    enabled: True
    state: started
