---
- name: Reload systemd configuration
  service:
    daemon_reload: True

- name: Reload udev rules
  command:
    cmd: udevadm control --reload-rules

- name: Restart xibo-linux service
  service:
    name: xibo-linux
    enabled: true
    state: restarted
